FROM python:3.9

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV APP_SETTINGS=prod
WORKDIR /telegrambot_mindset

RUN apt-get update

COPY ./requirements ./requirements
RUN --mount=type=cache,target=/root/.cache \
    pip install -r requirements/base.txt

COPY . .

RUN chmod +x run_bot.sh

ENTRYPOINT ["./run_bot.sh"]
