FROM python:3.9

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV APP_SETTINGS=dev
WORKDIR /pp_telegram_bot

RUN apt-get update

COPY ./requirements ./requirements
RUN --mount=type=cache,target=/root/.cache \
    pip install -r requirements/development.txt

COPY . .

RUN chmod +x run_bot.sh

ENTRYPOINT ["./run_bot.sh"]
