"""add tables new

Revision ID: 2ad40c12fa24
Revises: c2c15c19c51d
Create Date: 2022-04-25 21:57:56.769520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ad40c12fa24'
down_revision = 'c2c15c19c51d'
branch_labels = None
depends_on = None

act_options = ('desc_tags', 'desc', 'tags')
action = postgresql.ENUM(*act_options, name='action', create_type=False, schema='bot')
ya_options = ('check_token', 'upload_file')
yandex_action = postgresql.ENUM(*ya_options, name='yandex_action', create_type=False, schema='bot')
update_options = ('message', 'callback')
type_update = postgresql.ENUM(*update_options, name='type_update', create_type=False, schema='bot')


def upgrade():
    yandex_action.create(op.get_bind())
    type_update.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_yandex_disk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.BIGINT(), nullable=True),
    sa.Column('tg_chat_id', sa.BIGINT(), nullable=True),
    sa.Column('tg_message_id', sa.BIGINT(), nullable=True),
    sa.Column('token', sa.String(length=70), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('file_path', sa.String(length=250), nullable=True),
    sa.Column('yandex_action', yandex_action, nullable=True),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='bot'
    )
    op.create_index(op.f('ix_bot_tg_yandex_disk_is_success'), 'tg_yandex_disk', ['is_success'], unique=False, schema='bot')
    op.create_index(op.f('ix_bot_tg_yandex_disk_tg_chat_id'), 'tg_yandex_disk', ['tg_chat_id'], unique=False, schema='bot')
    op.create_index(op.f('ix_bot_tg_yandex_disk_tg_message_id'), 'tg_yandex_disk', ['tg_message_id'], unique=False, schema='bot')
    op.create_index(op.f('ix_bot_tg_yandex_disk_tg_user_id'), 'tg_yandex_disk', ['tg_user_id'], unique=False, schema='bot')
    op.add_column('tg_actions', sa.Column('tg_message_id', sa.BIGINT(), nullable=True), schema='bot')
    op.add_column('tg_actions', sa.Column('api_url', sa.String(length=250), nullable=True), schema='bot')
    op.add_column('tg_actions', sa.Column('is_success', sa.Boolean(), nullable=True), schema='bot')
    op.add_column('tg_actions', sa.Column('add_info', sa.String(length=500), nullable=True), schema='bot')
    op.create_index(op.f('ix_bot_tg_actions_api_url'), 'tg_actions', ['api_url'], unique=False, schema='bot')
    op.create_index(op.f('ix_bot_tg_actions_tg_message_id'), 'tg_actions', ['tg_message_id'], unique=False, schema='bot')
    op.drop_column('tg_actions', 'image_name', schema='bot')
    op.drop_column('tg_actions', 'image_type', schema='bot')
    op.drop_column('tg_actions', 'image_size', schema='bot')
    op.drop_column('tg_actions', 'action_type', schema='bot')
    op.add_column('tg_chat_history', sa.Column('type_update', type_update, nullable=True), schema='bot')
    op.add_column('tg_chat_history', sa.Column('callback_data', sa.String(length=150), nullable=True), schema='bot')
    op.add_column('tg_chat_history', sa.Column('from_bot', sa.Boolean(), nullable=True), schema='bot')
    op.add_column('tg_chat_history', sa.Column('is_image', sa.Boolean(), nullable=True), schema='bot')
    op.add_column('tg_chat_history', sa.Column('file_id', sa.String(length=150), nullable=True), schema='bot')
    op.add_column('tg_chat_history', sa.Column('text', sa.String(length=10000), nullable=True), schema='bot')
    op.add_column('tg_chat_history', sa.Column('caption', sa.String(length=10000), nullable=True), schema='bot')
    op.add_column('tg_chat_history', sa.Column('content_type', sa.String(length=50), nullable=True), schema='bot')
    op.add_column('tg_chat_history', sa.Column('mime_type', sa.String(length=150), nullable=True), schema='bot')
    op.add_column('tg_chat_history', sa.Column('is_delete', sa.Boolean(), nullable=True), schema='bot')
    op.create_index(op.f('ix_bot_tg_chat_history_file_id'), 'tg_chat_history', ['file_id'], unique=False, schema='bot')
    op.create_index(op.f('ix_bot_tg_chat_history_tg_msg_id'), 'tg_chat_history', ['tg_msg_id'], unique=False, schema='bot')
    op.drop_constraint('tg_chat_history_tg_user_id_fkey', 'tg_chat_history', schema='bot', type_='foreignkey')
    op.drop_column('tg_chat_history', 'user_msg', schema='bot')
    op.drop_column('tg_chat_history', 'bot_msg', schema='bot')
    action.drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade():
    action.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_chat_history', sa.Column('bot_msg', sa.VARCHAR(length=10000), autoincrement=False, nullable=True), schema='bot')
    op.add_column('tg_chat_history', sa.Column('user_msg', sa.VARCHAR(length=10000), autoincrement=False, nullable=True), schema='bot')
    op.create_foreign_key('tg_chat_history_tg_user_id_fkey', 'tg_chat_history', 'tg_users', ['tg_user_id'], ['tg_user_id'], source_schema='bot', referent_schema='bot', ondelete='CASCADE')
    op.drop_index(op.f('ix_bot_tg_chat_history_tg_msg_id'), table_name='tg_chat_history', schema='bot')
    op.drop_index(op.f('ix_bot_tg_chat_history_file_id'), table_name='tg_chat_history', schema='bot')
    op.drop_column('tg_chat_history', 'is_delete', schema='bot')
    op.drop_column('tg_chat_history', 'mime_type', schema='bot')
    op.drop_column('tg_chat_history', 'content_type', schema='bot')
    op.drop_column('tg_chat_history', 'caption', schema='bot')
    op.drop_column('tg_chat_history', 'text', schema='bot')
    op.drop_column('tg_chat_history', 'file_id', schema='bot')
    op.drop_column('tg_chat_history', 'is_image', schema='bot')
    op.drop_column('tg_chat_history', 'from_bot', schema='bot')
    op.drop_column('tg_chat_history', 'callback_data', schema='bot')
    op.drop_column('tg_chat_history', 'type_update', schema='bot')
    # op.add_column('tg_actions', sa.Column('action_type', postgresql.ENUM('desc_tags', 'desc', 'tags', name='action', schema='bot'), autoincrement=False, nullable=True), schema='bot')
    op.add_column('tg_actions', sa.Column('action_type', action, autoincrement=False, nullable=True), schema='bot')
    op.add_column('tg_actions', sa.Column('image_size', sa.INTEGER(), autoincrement=False, nullable=True), schema='bot')
    op.add_column('tg_actions', sa.Column('image_type', sa.VARCHAR(), autoincrement=False, nullable=True), schema='bot')
    op.add_column('tg_actions', sa.Column('image_name', sa.VARCHAR(), autoincrement=False, nullable=True), schema='bot')
    op.drop_index(op.f('ix_bot_tg_actions_tg_message_id'), table_name='tg_actions', schema='bot')
    op.drop_index(op.f('ix_bot_tg_actions_api_url'), table_name='tg_actions', schema='bot')
    op.drop_column('tg_actions', 'add_info', schema='bot')
    op.drop_column('tg_actions', 'is_success', schema='bot')
    op.drop_column('tg_actions', 'api_url', schema='bot')
    op.drop_column('tg_actions', 'tg_message_id', schema='bot')
    op.drop_index(op.f('ix_bot_tg_yandex_disk_tg_user_id'), table_name='tg_yandex_disk', schema='bot')
    op.drop_index(op.f('ix_bot_tg_yandex_disk_tg_message_id'), table_name='tg_yandex_disk', schema='bot')
    op.drop_index(op.f('ix_bot_tg_yandex_disk_tg_chat_id'), table_name='tg_yandex_disk', schema='bot')
    op.drop_index(op.f('ix_bot_tg_yandex_disk_is_success'), table_name='tg_yandex_disk', schema='bot')
    op.drop_table('tg_yandex_disk', schema='bot')
    yandex_action.drop(op.get_bind())
    type_update.drop(op.get_bind())

    # ### end Alembic commands ###
