"""change some attrs

Revision ID: bec446ef700d
Revises: 2ad40c12fa24
Create Date: 2022-05-02 17:21:07.599629

"""
from alembic import op

import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bec446ef700d'
down_revision = '2ad40c12fa24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_actions', sa.Column('tg_msg_id', sa.BIGINT(), nullable=True), schema='bot')
    op.add_column('tg_actions', sa.Column('response', sa.String(length=20000), nullable=True), schema='bot')
    op.drop_index('ix_bot_tg_actions_tg_message_id', table_name='tg_actions', schema='bot')
    op.create_index(op.f('ix_bot_tg_actions_tg_msg_id'), 'tg_actions', ['tg_msg_id'], unique=False, schema='bot')
    op.drop_column('tg_actions', 'responce', schema='bot')
    op.drop_column('tg_actions', 'tg_message_id', schema='bot')
    op.add_column('tg_groups', sa.Column('create_at', sa.DateTime(), nullable=True), schema='bot')
    op.add_column('tg_yandex_disk', sa.Column('tg_msg_id', sa.BIGINT(), nullable=True), schema='bot')
    op.add_column('tg_yandex_disk', sa.Column('create_at', sa.DateTime(), nullable=True), schema='bot')
    op.drop_index('ix_bot_tg_yandex_disk_tg_message_id', table_name='tg_yandex_disk', schema='bot')
    op.create_index(op.f('ix_bot_tg_yandex_disk_tg_msg_id'), 'tg_yandex_disk', ['tg_msg_id'], unique=False, schema='bot')
    op.drop_column('tg_yandex_disk', 'tg_message_id', schema='bot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_yandex_disk', sa.Column('tg_message_id', sa.BIGINT(), autoincrement=False, nullable=True), schema='bot')
    op.drop_index(op.f('ix_bot_tg_yandex_disk_tg_msg_id'), table_name='tg_yandex_disk', schema='bot')
    op.create_index('ix_bot_tg_yandex_disk_tg_message_id', 'tg_yandex_disk', ['tg_message_id'], unique=False, schema='bot')
    op.drop_column('tg_yandex_disk', 'create_at', schema='bot')
    op.drop_column('tg_yandex_disk', 'tg_msg_id', schema='bot')
    op.drop_column('tg_groups', 'create_at', schema='bot')
    op.add_column('tg_actions', sa.Column('tg_message_id', sa.BIGINT(), autoincrement=False, nullable=True), schema='bot')
    op.add_column('tg_actions', sa.Column('responce', sa.VARCHAR(length=20000), autoincrement=False, nullable=True), schema='bot')
    op.drop_index(op.f('ix_bot_tg_actions_tg_msg_id'), table_name='tg_actions', schema='bot')
    op.create_index('ix_bot_tg_actions_tg_message_id', 'tg_actions', ['tg_message_id'], unique=False, schema='bot')
    op.drop_column('tg_actions', 'response', schema='bot')
    op.drop_column('tg_actions', 'tg_msg_id', schema='bot')
    # ### end Alembic commands ###
